CREATE TABLE IF NOT EXISTS PTransaction (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pid INTEGER NOT NULL,

    ttype INTEGER NOT NULL,
    value REAL NOT NULL,
    timestamp REAL NOT NULL,

    FOREIGN KEY(pid) REFERENCES Punter(uid) ON DELETE CASCADE
);
