CREATE TABLE IF NOT EXISTS Investment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    wallet TEXT NOT NULL,
    bet INTEGER NOT NULL,

    FOREIGN KEY(wallet) REFERENCES Wallet(cpf_owner),
    FOREIGN KEY(bet) REFERENCES Bet(bid)
);

