CREATE TABLE IF NOT EXISTS User (
    uid INTEGER PRIMARY KEY AUTOINCREMENT,

    utype INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,

    login TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

