CREATE TABLE IF NOT EXISTS Punter (
    uid INTEGER PRIMARY KEY,

    profit REAL DEFAULT 0.0,
    loss REAL DEFAULT 0.0,
    wallet INTEGER NOT NULL,

    FOREIGN KEY(wallet) REFERENCES WALLET(wid) ON DELETE CASCADE,
    FOREIGN KEY(uid) REFERENCES User(uid) ON DELETE CASCADE
);

